blank_issues_enabled: true
contact_links:
  - name: Test Framework Issue
    url: https://github.com/nunit/nunit/issues/new
    about: For issues encountered when using the test framework
  - name: Console Runner Issue
    url: https://github.com/nunit/nunit-console/issues/new
    about: For issues encountered when using the console runner
  - name: VS Test Adapter
    url: https://github.com/nunit/nunit3-vs-adapter/issues/new
    about: For issues encountered when using the NUnit Visual Studio Test Adapter
  - name: Issue while using another NUnit project / component
    url: https://github.com/nunit#org-repositories
    about: Please find the appropriate repository at this list and file an issue there.
